
include equates.a86
		cseg

		extrn	bdos_rsx:near
	
		dseg
		extrn	dirname_0:word

		public	proc1
;
; First process
;
proc1		dw 0	
		dw offset proc2		; DATA XREF: bdos:0044r bdos:0050w
		rw 2
		db 'Init    '
		db 0
		dw offset dirname_0
		rw 3
		db '$'

		rb 45
		db 1
		rw 5
		dw offset bdos_rsx
		rb 10Ch

proc2		dw	0
		dw	proc3
		db	2, 1
		rb	15Ah

proc3		dw	0
		dw 	proc4
		db	2, 2
		rb	15Ah


proc4		dw	0
		dw	0
		db 	2, 3
		rb	15Ah

		rb	0A0h



